version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.20

    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - .next/cache

      - run:
          command: yarn lint

      - run: yarn test

      - run: yarn build

workflows:
  build:
    jobs:
      - build
