version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ''

  GHA_Action:
    type: string
    default: ''

  GHA_Event:
    type: string
    default: ''

  GHA_Meta:
    type: string
    default: ''

jobs:
  test:
    docker:
      - image: cimg/node:14.20

    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - .next/cache

      - run:
          name: tests
          command: |
            yarn lint
            yarn test

      - run:
          name: GHA
          command: |
            echo "GHA_Actor: $GHA_Actor"
            echo "GHA_Action: $GHA_Action"
            echo "GHA_Event: $GHA_Event"
            echo "GHA_Meta: $GHA_Meta"

workflows:
  test:
    jobs:
      - test
