version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: 'foo actor'

  GHA_Action:
    type: string
    default: 'foo action'

  GHA_Event:
    type: string
    default: 'foo event'

  GHA_Meta:
    type: string
    default: 'foo meta'

jobs:
  GHA:
    parameters:
      GHA_Actor:
        type: string
        default: 'foo actor'

      GHA_Action:
        type: string
        default: 'foo action'

      GHA_Event:
        type: string
        default: 'foo event'

      GHA_Meta:
        type: string
        default: 'foo meta'

    docker:
      - image: cimg/node:14.20

    steps:
      - run:
          name: echo GHA
          command: |
            echo "GHA_Actor: << parameters.GHA_Actor >>"
            echo "GHA_Action: << parameters.GHA_Action >>"
            echo "GHA_Event: << parameters.GHA_Event >>"
            echo "GHA_Meta: << parameters.GHA_Meta >>"

  test:
    docker:
      - image: cimg/node:14.20

    steps:
      - checkout

      - restore_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - .next/cache

      - run:
          name: tests
          command: |
            yarn lint
            yarn test

workflows:
  test:
    jobs:
      - GHA
      # - test
