on:
  issue_comment:
    types: [created]

  pull_request:
    types: [created, edited, synchronise]

jobs:
  job-branch:
    runs-on: ubuntu-latest

    steps:
      - name: get
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: print env
        run: |
          echo "base_ref_branch: ${{ steps.branch-name.outputs.base_ref_branch }}"
          echo "current_branch: ${{ steps.branch-name.outputs.current_branch }}"
          echo "default_branch: ${{ steps.branch-name.outputs.default_branch }}"
          echo "head_ref_branch: ${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "is_default: ${{ steps.branch-name.outputs.is_default }}"
          echo "is_tag: ${{ steps.branch-name.outputs.is_tag }}"
          echo "ref_branch: ${{ steps.branch-name.outputs.ref_branch }}"
          echo "tag: ${{ steps.branch-name.outputs.tag }}"
