on:
  issue_comment:
    types: [created]

  pull_request:
    types: [created, edited, synchronise]

jobs:
  pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: get branch
        id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1

      - name: print output
        run: |
          echo "base_ref: ${{ steps.comment-branch.outputs.base_ref }}"
          echo "base_sha: ${{ steps.comment-branch.outputs.base_sha }}"
          echo "head_ref: ${{ steps.comment-branch.outputs.head_ref }}"
          echo "head_sha: ${{ steps.comment-branch.outputs.head_sha }}"
