name: GHA

on:
  pull_request:
    types:
      - edited
      - labeled
      - unlabeled

jobs:
  trigger-circleci:
    # if: ${{ github.event.issue.pull_request }}

    runs-on: ubuntu-latest

    steps:
      - name: branch name
        run: |
          echo $GITHUB_HEAD_REF
          node -e 'Object.keys(process.env).sort().forEach(k => {
            console.log("-".repeat(10))
            console.log(k)
            console.log(process.env[k])
          })'

      # - name: CircleCI Trigger on Pull Request
      #   id: foobar
      #   uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
      #   env:
      #     CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
