name: GHA

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest

    steps:
      - name: print GHA
        if: contains(github.event.pull_request.labels.*.name, 'foobar')
        run: |
          echo $GITHUB_HEAD_REF
          cat $GITHUB_EVENT_PATH

      - name: CircleCI Trigger on Pull Request
        if: contains(github.event.pull_request.labels.*.name, 'foobar')
        id: foobar
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
